[[redirects]]
from = "https://master--thomasbnt.netlify.app/"
to = "https://awesomewebmonetization.netlify.app/"
status = 301
force = true
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"